# Generated by Django 6.1.1 on 2026-10-03 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='main/images/')),
                ('tiktok_url', models.URLField(blank=True, max_length=500)),
                ('genre', models.CharField(choices=[('crea', 'Crea'), ('musical', 'Musical'), ('rekenen', 'Rekenen'), ('spelling', 'Spelling')], default='crea', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first. Leave at 0 to put a new item at the top.')),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='main/files/')),
                ('external_url', models.URLField(blank=True, help_text='Use this instead of uploading, e.g. a YouTube link.', max_length=500)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='gallery.galleryitem')),
            ],
        ),
    ]
