from django.shortcuts import render
import json

def home_view(request):
    gallery_items = [
        {   # Pepernoten proeverij
            'id': 1,
            'title': 'Pepernoten proeverij',
            'description': 'In deze les doen de leerlingen een proeverij met verschillende soorten pepernoten en kruidnoten. Ze onderzoeken de producten met hun zintuigen en verwerken hun bevindingen in eenvoudige observaties en vergelijkingen.',
            'image': {'url': 'main/images/IMG_2777.JPG'},
            'tiktok_url': 'https://www.tiktok.com/@bestofbart/video/7578943053881298208',
            'genre': 'rekenen',
            'files': [{'url': '/media/main/files/pepernotenproeverij/pepernotenproeverij-blad'}],
        },
        {   # t'Sexy fokschaap
            'id': 2,
            'title': "'t Sexy fokschaap",
            'description': "Een creatieve spellingles waarin leerlingen een visuele en grappige uitwerking maken van de regel van 't fokschaap. Door tekenen en ontwerpen wordt de werkwoordspelling beter onthouden.",
            'image': {'url': 'main/images/IMG_2778.JPG'},
            'tiktok_url': 'https://www.tiktok.com/@bestofbart/video/7574094689893223713',
            'genre': 'spelling',
            'files': [{'url': '/media/main/files/t-sexy-fokschaap/t-sexy-fokschaap-uitleg'}],
        },
        {   # Maak je eigen prentenboek
            'id': 3,
            'title': "Maak je eigen prentenboek",
            'description': 'De leerlingen ontwerpen hun eigen prentenboek. Ze bedenken een verhaal, maken zelf de illustraties en zetten alles digitaal in een prentenboekvorm.',
            'image': {'url': 'main/images/IMG_2779.JPG'},            
            'tiktok_url': 'https://www.tiktok.com/@bestofbart/video/7559623858534337824',
            'genre': 'crea',
            'files': [{'url': '/media/main/files/prentenboek/prentenboek-blad'}],
        },
        {   # Neon lights schilderen
            'id': 4,
            'title': 'Neon lights schilderen',
            'description': 'In deze crea-les maken leerlingen een schilderij met een neon-licht-effect. Met contrast en kleurgebruik ontstaat een opvallend, lichtgevend resultaat.',
            'image': {'url': 'main/images/IMG_2780.JPG'},
            'tiktok_url': 'https://www.tiktok.com/@bestofbart/video/7552943116949523744',
            'genre': 'crea',
            'files': [{'url': '/media/main/files/neon-lights/neon-lights-uitleg'}],
        },
        {   # Moederdagcadeau
            'id': 5,
            'title': 'Moederdagcadeau',
            'description': "Leerlingen ontwerpen een persoonlijke wikkel voor een chocoladereep en maken een bijpassende 'golden ticket'. Het eindresultaat is een creatief en persoonlijk Moederdagcadeau.",
            'image': {'url': 'main/images/IMG_2781.JPG'},
            'tiktok_url': 'https://www.tiktok.com/@bestofbart/video/7501702548282150166',
            'genre': 'crea',
            'files': [{'url': '/media/main/files/moederdag/moederdag-blad'}],
        },
        {   # Emoji's vouwen
            'id': 6,
            'title': "Emoji's vouwen",
            'description': 'In deze les vouwen leerlingen papier tot herkenbare emoji-figuren. Er wordt gewerkt aan nauwkeurig vouwen, vorm en expressie.',
            'image': {'url': 'main/images/IMG_2782.JPG'},
            'tiktok_url': 'https://www.tiktok.com/@bestofbart/video/7466871827034508567',
            'genre': 'crea',
            'files': [{'url': '/media/main/files/emojis-vouwen/emojis-vouwen-uitleg'}],
        },
        {   # Rocky Road
            'id': 7,
            'title': "Rocky Road",
            'description': 'De klas maakt samen een Sinterklaas-variant van Rocky Road. Leerlingen volgen een recept en verwerken verschillende ingrediënten tot een feestelijk eindproduct.',
            'image': {'url': 'main/images/IMG_2783.JPG'},
            'tiktok_url': 'https://www.tiktok.com/@bestofbart/video/7443536203560881430',
            'genre': 'crea',
            'files': [{'url': '/media/main/files/rocky-road/rocky-road-uitleg'}],
        },
        {   # Schuifpuzzel maken
            'id': 8,
            'title': "Schuifpuzzel maken",
            'description': 'Leerlingen ontwerpen en maken hun eigen schuifpuzzel. Ze werken aan beeld, indeling en logisch nadenken om een speelbare puzzel te creëren.',
            'image': {'url': 'main/images/IMG_2784.JPG'},
            'tiktok_url': 'https://www.tiktok.com/@bestofbart/video/7464288494601440534',
            'genre': 'crea',
            'files': [{'url': '/media/main/files/schuifpuzzel/schuifpuzzel-blad'}, {'url': '/media/main/files/schuifpuzzel/schuifpuzzel-uitleg'}],
        },
        {   # Mascotte maken
            'id': 9,
            'title': "Mascotte maken",
            'description': 'In deze lessenserie ontwerpen leerlingen een eigen mascotte. Ze tekenen het ontwerp, kleien het figuur en schilderen het uiteindelijk af.',
            'image': {'url': 'main/images/IMG_2785.JPG'},
            'tiktok_url': 'https://www.tiktok.com/@bestofbart/video/7426633807169719585',
            'genre': 'crea',
            'files': [{'url': '/media/main/files/mascotte/mascotte-blad'}, {'url': '/media/main/files/mascotte/mascotte-uitleg'}],
        },
        {   # Schatkaarten maken
            'id': 10,
            'title': "Schatkaarten maken",
            'description': "Leerlingen maken een schatkaart op 'verouderd' papier. Ze geven hun kaart vorm met symbolen, routes en fantasierijke details.",
            'image': {'url': 'main/images/IMG_2786.JPG'},
            'tiktok_url': 'https://www.tiktok.com/@bestofbart/video/7277228115951209760',
            'genre': 'crea',
            'files': [{'url': '/media/main/files/schatkaarten/schatkaarten-uitleg'}],
        },
        {   # Adventkalender maken
            'id': 11,
            'title': "Adventkalender maken",
            'description': "In deze les maken leerlingen een adventskalender in de vorm van een decemberdorpje. Elk huisje staat voor een dag en bevat een kleine verrassing of opdracht.",
            'image': {'url': 'main/images/IMG_2787.JPG'},
            'tiktok_url': 'https://www.tiktok.com/@bestofbart/video/7172094048319196421',
            'genre': 'crea',
            'files': [{'url': '/media/main/files/adventkalender/adventkalender-uitleg'}, {'url': '/media/main/files/adventkalender/adventkalender-uitleg'}],
        },
        {   # Expeditie eiland maken
            'id': 12,
            'title': "Expeditie eiland maken",
            'description': "Leerlingen ontwerpen en bouwen een eigen eiland geïnspireerd op Expeditie Robinson. Ze werken met reliëf, materialen en fantasie om hun eiland vorm te geven.",
            'image': {'url': 'main/images/IMG_2788.JPG'},
            'tiktok_url': 'https://www.tiktok.com/@bestofbart/video/7379850710663351585',
            'genre': 'crea',
            'files': [{'url': '/media/main/files/expeditie-eiland/expeditie-eiland-uitleg'}],
        },
        {   # Skyline schilderen
            'id': 13,
            'title': "Skyline schilderen",
            'description': "Leerlingen schilderen een skyline tegen een zonsondergang. De focus ligt op kleurverloop, silhouetten en dieptewerking.",
            'image': {'url': 'main/images/IMG_2789.JPG'},
            'tiktok_url': 'https://www.tiktok.com/@bestofbart/video/7418997114086231328',
            'genre': 'crea',
            'files': [{'url': '/media/main/files/skyline/skyline-uitleg'}],
        },
        {   # 't Kofschip X
            'id': 14,
            'title': "'t Kofschip X",
            'description': "Een spellingles waarin leerlingen de regel van 't kofschip X visueel en praktisch verwerken. Door het maken van een concreet product wordt de regel beter onthouden.",
            'image': {'url': 'main/images/IMG_2790.JPG'},
            'tiktok_url': 'https://www.tiktok.com/@bestofbart/video/7296574980156820769',
            'genre': 'spelling',
            'files': [{'url': '/media/main/files/t-kofschip-x/t-kofschip-x-uitleg'}],
        },
    ]
    
    for item in gallery_items:
        item['files'] = json.dumps(item['files'])
    
    # Show only first 4 items on home page
    return render(request, 'home.html', {'gallery_items': gallery_items[:4], 'total_items': len(gallery_items)})

def items_view(request):
    gallery_items = [
        {   # Pepernoten proeverij
            'id': 1,
            'title': 'Pepernoten proeverij',
            'description': 'In deze les doen de leerlingen een proeverij met verschillende soorten pepernoten en kruidnoten. Ze onderzoeken de producten met hun zintuigen en verwerken hun bevindingen in eenvoudige observaties en vergelijkingen.',
            'image': {'url': 'main/images/IMG_2777.JPG'},
            'tiktok_url': 'https://www.tiktok.com/@bestofbart/video/7578943053881298208',
            'genre': 'rekenen',
            'files': [{'url': '/media/main/files/pepernotenproeverij/pepernotenproeverij-blad'}],
        },
        {   # t'Sexy fokschaap
            'id': 2,
            'title': "'t Sexy fokschaap",
            'description': "Een creatieve spellingles waarin leerlingen een visuele en grappige uitwerking maken van de regel van 't fokschaap. Door tekenen en ontwerpen wordt de werkwoordspelling beter onthouden.",
            'image': {'url': 'main/images/IMG_2778.JPG'},
            'tiktok_url': 'https://www.tiktok.com/@bestofbart/video/7574094689893223713',
            'genre': 'spelling',
            'files': [{'url': '/media/main/files/t-sexy-fokschaap/t-sexy-fokschaap-uitleg'}],
        },
        {   # Maak je eigen prentenboek
            'id': 3,
            'title': "Maak je eigen prentenboek",
            'description': 'De leerlingen ontwerpen hun eigen prentenboek. Ze bedenken een verhaal, maken zelf de illustraties en zetten alles digitaal in een prentenboekvorm.',
            'image': {'url': 'main/images/IMG_2779.JPG'},            
            'tiktok_url': 'https://www.tiktok.com/@bestofbart/video/7559623858534337824',
            'genre': 'crea',
            'files': [{'url': '/media/main/files/prentenboek/prentenboek-blad'}],
        },
        {   # Neon lights schilderen
            'id': 4,
            'title': 'Neon lights schilderen',
            'description': 'In deze crea-les maken leerlingen een schilderij met een neon-licht-effect. Met contrast en kleurgebruik ontstaat een opvallend, lichtgevend resultaat.',
            'image': {'url': 'main/images/IMG_2780.JPG'},
            'tiktok_url': 'https://www.tiktok.com/@bestofbart/video/7552943116949523744',
            'genre': 'crea',
            'files': [{'url': '/media/main/files/neon-lights/neon-lights-uitleg'}],
        },
        {   # Moederdagcadeau
            'id': 5,
            'title': 'Moederdagcadeau',
            'description': "Leerlingen ontwerpen een persoonlijke wikkel voor een chocoladereep en maken een bijpassende 'golden ticket'. Het eindresultaat is een creatief en persoonlijk Moederdagcadeau.",
            'image': {'url': 'main/images/IMG_2781.JPG'},
            'tiktok_url': 'https://www.tiktok.com/@bestofbart/video/7501702548282150166',
            'genre': 'crea',
            'files': [{'url': '/media/main/files/moederdag/moederdag-blad'}],
        },
        {   # Emoji's vouwen
            'id': 6,
            'title': "Emoji's vouwen",
            'description': 'In deze les vouwen leerlingen papier tot herkenbare emoji-figuren. Er wordt gewerkt aan nauwkeurig vouwen, vorm en expressie.',
            'image': {'url': 'main/images/IMG_2782.JPG'},
            'tiktok_url': 'https://www.tiktok.com/@bestofbart/video/7466871827034508567',
            'genre': 'crea',
            'files': [{'url': '/media/main/files/emojis-vouwen/emojis-vouwen-uitleg'}],
        },
        {   # Rocky Road
            'id': 7,
            'title': "Rocky Road",
            'description': 'De klas maakt samen een Sinterklaas-variant van Rocky Road. Leerlingen volgen een recept en verwerken verschillende ingrediënten tot een feestelijk eindproduct.',
            'image': {'url': 'main/images/IMG_2783.JPG'},
            'tiktok_url': 'https://www.tiktok.com/@bestofbart/video/7443536203560881430',
            'genre': 'crea',
            'files': [{'url': '/media/main/files/rocky-road/rocky-road-uitleg'}],
        },
        {   # Schuifpuzzel maken
            'id': 8,
            'title': "Schuifpuzzel maken",
            'description': 'Leerlingen ontwerpen en maken hun eigen schuifpuzzel. Ze werken aan beeld, indeling en logisch nadenken om een speelbare puzzel te creëren.',
            'image': {'url': 'main/images/IMG_2784.JPG'},
            'tiktok_url': 'https://www.tiktok.com/@bestofbart/video/7464288494601440534',
            'genre': 'crea',
            'files': [{'url': '/media/main/files/schuifpuzzel/schuifpuzzel-blad'}, {'url': '/media/main/files/schuifpuzzel/schuifpuzzel-uitleg'}],
        },
        {   # Mascotte maken
            'id': 9,
            'title': "Mascotte maken",
            'description': 'In deze lessenserie ontwerpen leerlingen een eigen mascotte. Ze tekenen het ontwerp, kleien het figuur en schilderen het uiteindelijk af.',
            'image': {'url': 'main/images/IMG_2785.JPG'},
            'tiktok_url': 'https://www.tiktok.com/@bestofbart/video/7426633807169719585',
            'genre': 'crea',
            'files': [{'url': '/media/main/files/mascotte/mascotte-blad'}, {'url': '/media/main/files/mascotte/mascotte-uitleg'}],
        },
        {   # Schatkaarten maken
            'id': 10,
            'title': "Schatkaarten maken",
            'description': "Leerlingen maken een schatkaart op 'verouderd' papier. Ze geven hun kaart vorm met symbolen, routes en fantasierijke details.",
            'image': {'url': 'main/images/IMG_2786.JPG'},
            'tiktok_url': 'https://www.tiktok.com/@bestofbart/video/7277228115951209760',
            'genre': 'crea',
            'files': [{'url': '/media/main/files/schatkaarten/schatkaarten-uitleg'}],
        },
        {   # Adventkalender maken
            'id': 11,
            'title': "Adventkalender maken",
            'description': "In deze les maken leerlingen een adventskalender in de vorm van een decemberdorpje. Elk huisje staat voor een dag en bevat een kleine verrassing of opdracht.",
            'image': {'url': 'main/images/IMG_2787.JPG'},
            'tiktok_url': 'https://www.tiktok.com/@bestofbart/video/7172094048319196421',
            'genre': 'crea',
            'files': [{'url': '/media/main/files/adventkalender/adventkalender-uitleg'}, {'url': '/media/main/files/adventkalender/adventkalender-uitleg'}],
        },
        {   # Expeditie eiland maken
            'id': 12,
            'title': "Expeditie eiland maken",
            'description': "Leerlingen ontwerpen en bouwen een eigen eiland geïnspireerd op Expeditie Robinson. Ze werken met reliëf, materialen en fantasie om hun eiland vorm te geven.",
            'image': {'url': 'main/images/IMG_2788.JPG'},
            'tiktok_url': 'https://www.tiktok.com/@bestofbart/video/7379850710663351585',
            'genre': 'crea',
            'files': [{'url': '/media/main/files/expeditie-eiland/expeditie-eiland-uitleg'}],
        },
        {   # Skyline schilderen
            'id': 13,
            'title': "Skyline schilderen",
            'description': "Leerlingen schilderen een skyline tegen een zonsondergang. De focus ligt op kleurverloop, silhouetten en dieptewerking.",
            'image': {'url': 'main/images/IMG_2789.JPG'},
            'tiktok_url': 'https://www.tiktok.com/@bestofbart/video/7418997114086231328',
            'genre': 'crea',
            'files': [{'url': '/media/main/files/skyline/skyline-uitleg'}],
        },
        {   # 't Kofschip X
            'id': 14,
            'title': "'t Kofschip X",
            'description': "Een spellingles waarin leerlingen de regel van 't kofschip X visueel en praktisch verwerken. Door het maken van een concreet product wordt de regel beter onthouden.",
            'image': {'url': 'main/images/IMG_2790.JPG'},
            'tiktok_url': 'https://www.tiktok.com/@bestofbart/video/7296574980156820769',
            'genre': 'spelling',
            'files': [{'url': '/media/main/files/t-kofschip-x/t-kofschip-x-uitleg'}],
        },
    ]
    
    for item in gallery_items:
        item['files'] = json.dumps(item['files'])
    
    return render(request, 'items.html', {'gallery_items': gallery_items})

def contact_view(request):
    return render(request, "contact.html")